// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BPnnML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


    }
}
